- name: Run 'show version' command on Cisco devices
  hosts: cisco_devices
  gather_facts: no
  tasks:
    - name: Run 'show version'
      cisco.ios.ios_command:
        commands:
          - show version
      register: result

    - name: Display result
      debug:
        var: result
