- name: cisco_sh_ver
  hosts: all
  collections:
    - name: cisco.ios
  gather_facts: true 
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version       
  - name: show run on remote devices
    become: true
    cisco.ios.ios_command:
     commands: 
     - show run
